Exception ignored in: <function Connection.__del__ at 0x7fdc3b9025f0>
Traceback (most recent call last):
  File "/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/db/connection.py", line 185, in __del__
UserWarning: Unclosed <firebolt.db.connection.Connection object at 0x7fdc3afbded0> 140583859117776
